version: '3.8'

services:
  # Frontend React app
  frontend:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  # FastAPI backend service
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge